spring.application.name=styleathome-backend

spring.datasource.url=jdbc:mysql://localhost:3306/styleathome?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=madan
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=9a3e6afb74c4d9f8e4e9f73b2c1d5a8df23b6c7dee9f43b5a9cd28ef7492bd8c
jwt.expiration=86400000
